#include "../include/tuil_fonts.h"

static const char* char_ptrs_upper_doom[26][8] = {
    // A
    {
        "  ___  ",
        " / _ \\ ",
        "/ /_\\ \\",
        "|  _  |",
        "| | | |",
        "\\_| |_/",
        "       ",
        "       ",
    },
    // B
    {
        "______ ",
        "| ___ \\",
        "| |_/ /",
        "| ___ \\",
        "| |_/ /",
        "\\____/ ",
        "       ",
        "       ",
    },
    // C
    {
        " _____ ",
        "/  __ \\",
        "| /  \\/",
        "| |    ",
        "| \\__/\\",
        " \\____/",
        "       ",
        "       ",
    },
    // D
    {
        "______ ",
        "|  _  \\",
        "| | | |",
        "| | | |",
        "| |/ / ",
        "|___/  ",
        "       ",
        "       ",
    },
    // E
    {
        " _____ ",
        "|  ___|",
        "| |__  ",
        "|  __| ",
        "| |___ ",
        "\\____/ ",
        "       ",
        "       ",
    },
    // F
    {
        "______ ",
        "|  ___|",
        "| |_   ",
        "|  _|  ",
        "| |    ",
        "\\_|    ",
        "       ",
        "       ",
    },
    // G
    {
        " _____ ",
        "|  __ \\",
        "| |  \\/",
        "| | __ ",
        "| |_\\ \\",
        " \\____/",
        "       ",
        "       ",
    },
    // H
    {
        " _   _ ",
        "| | | |",
        "| |_| |",
        "|  _  |",
        "| | | |",
        "\\_| |_/",
        "       ",
        "       ",
    },
    // I
    {
        " _____ ",
        "|_   _|",
        "  | |  ",
        "  | |  ",
        " _| |_ ",
        " \\___/ ",
        "       ",
        "       ",
    },
    // J
    {
        "   ___ ",
        "  |_  |",
        "    | |",
        "    | |",
        "/\\__/ /",
        "\\____/ ",
        "       ",
        "       ",
    },
    // K
    {
        " _   __",
        "| | / /",
        "| |/ / ",
        "|    \\ ",
        "| |\\  \\",
        "\\_| \\_/",
        "       ",
        "       ",
    },
    // L
    {
        " _     ",
        "| |    ",
        "| |    ",
        "| |    ",
        "| |____",
        "\\_____/",
        "       ",
        "       ",
    },
    // M
    {
        "___  ___",
        "|  \\/  |",
        "| .  . |",
        "| |\\/| |",
        "| |  | |",
        "\\_|  |_/",
        "        ",
        "        ",
    },
    // N
    {
        " _   _ ",
        "| \\ | |",
        "|  \\| |",
        "| . ` |",
        "| |\\  |",
        "\\_| \\_/",
        "       ",
        "       ",
    },
    // O
    {
        " _____ ",
        "|  _  |",
        "| | | |",
        "| | | |",
        "\\ \\_/ /",
        " \\___/ ",
        "       ",
        "       ",
    },
    // P
    {
        "______ ",
        "| ___ \\",
        "| |_/ /",
        "|  __/ ",
        "| |    ",
        "\\_|    ",
        "       ",
        "       ",
    },
    // Q
    {
        " _____ ",
        "|  _  |",
        "| | | |",
        "| | | |",
        "\\ \\/' /",
        " \\_/\\_\\",
        "       ",
        "       ",
    },
    // R
    {
        "______ ",
        "| ___ \\",
        "| |_/ /",
        "|    / ",
        "| |\\ \\ ",
        "\\_| \\_|",
        "       ",
        "       ",
    },
    // S
    {
        " _____ ",
        "/  ___|",
        "\\ `--. ",
        " `--. \\",
        "/\\__/ /",
        "\\____/ ",
        "       ",
        "       ",
    },
    // T
    {
        " _____ ",
        "|_   _|",
        "  | |  ",
        "  | |  ",
        "  | |  ",
        "  \\_/  ",
        "       ",
        "       ",
    },
    // U
    {
        " _   _ ",
        "| | | |",
        "| | | |",
        "| | | |",
        "| |_| |",
        " \\___/ ",
        "       ",
        "       ",
    },
    // V
    {
        " _   _ ",
        "| | | |",
        "| | | |",
        "| | | |",
        "\\ \\_/ /",
        " \\___/ ",
        "       ",
        "       ",
    },
    // W
    {
        " _    _ ",
        "| |  | |",
        "| |  | |",
        "| |/\\| |",
        "\\  /\\  /",
        " \\/  \\/ ",
        "        ",
        "        ",
    },
    // X
    {
        "__   __",
        "\\ \\ / /",
        " \\ V / ",
        " /   \\ ",
        "/ /^\\ \\",
        "\\/   \\/",
        "       ",
        "       ",
    },
    // Y
    {
        "__   __",
        "\\ \\ / /",
        " \\ V / ",
        "  \\ /  ",
        "  | |  ",
        "  \\_/  ",
        "       ",
        "       ",
    },
    // Z
    {
        " ______",
        "|___  /",
        "   / / ",
        "  / /  ",
        "./ /___",
        "\\_____/",
        "       ",
        "       ",
    },
};

static const char* char_ptrs_lower_doom[26][8] = {
    // a
    {
        "       ",
        "       ",
        "  __ _ ",
        " / _` |",
        "| (_| |",
        " \\__,_|",
        "       ",
        "       ",
    },
    // b
    {
        " _     ",
        "| |    ",
        "| |__  ",
        "| '_ \\ ",
        "| |_) |",
        "|_.__/ ",
        "       ",
        "       ",
    },
    // c
    {
        "      ",
        "      ",
        "  ___ ",
        " / __|",
        "| (__ ",
        " \\___|",
        "      ",
        "      ",
    },
    // d
    {
        "     _ ",
        "    | |",
        "  __| |",
        " / _` |",
        "| (_| |",
        " \\__,_|",
        "       ",
        "       ",
    },
    // e
    {
        "      ",
        "      ",
        "  ___ ",
        " / _ \\",
        "|  __/",
        " \\___|",
        "      ",
        "      ",
    },
    // f
    {
        "  __ ",
        " / _|",
        "| |_ ",
        "|  _|",
        "| |  ",
        "|_|  ",
        "     ",
        "     ",
    },
    // g
    {
        "       ",
        "       ",
        "  __ _ ",
        " / _` |",
        "| (_| |",
        " \\__, |",
        "  __/ |",
        " |___/ ",
    },
    // h
    {
        " _     ",
        "| |    ",
        "| |__  ",
        "| '_ \\ ",
        "| | | |",
        "|_| |_|",
        "       ",
        "       ",
    },
    // i
    {
        " _ ",
        "(_)",
        " _ ",
        "| |",
        "| |",
        "|_|",
        "   ",
        "   ",
    },
    // j
    {
        "   _ ",
        "  (_)",
        "   _ ",
        "  | |",
        "  | |",
        "  | |",
        " _/ |",
        "|__/ ",
    },
    // k
    {
        " _    ",
        "| |   ",
        "| | __",
        "| |/ /",
        "|   < ",
        "|_|\\_\\",
        "      ",
        "      ",
    },
    // l
    {
        " _ ",
        "| |",
        "| |",
        "| |",
        "| |",
        "|_|",
        "   ",
        "   ",
    },
    // m
    {
        "           ",
        "           ",
        " _ __ ___  ",
        "| '_ ` _ \\ ",
        "| | | | | |",
        "|_| |_| |_|",
        "           ",
        "           ",
    },
    // n
    {
        "       ",
        "       ",
        " _ __  ",
        "| '_ \\ ",
        "| | | |",
        "|_| |_|",
        "       ",
        "       ",
    },
    // o
    {
        "       ",
        "       ",
        "  ___  ",
        " / _ \\ ",
        "| (_) |",
        " \\___/ ",
        "       ",
        "       ",
    },
    // p
    {
        "       ",
        "       ",
        " _ __  ",
        "| '_ \\ ",
        "| |_) |",
        "| .__/ ",
        "| |    ",
        "|_|    ",
    },
    // q
    {
        "       ",
        "       ",
        "  __ _ ",
        " / _` |",
        "| (_| |",
        " \\__, |",
        "    | |",
        "    |_|",
    },
    // r
    {
        "      ",
        "      ",
        " _ __ ",
        "| '__|",
        "| |   ",
        "|_|   ",
        "      ",
        "      ",
    },
    // s
    {
        "     ",
        "     ",
        " ___ ",
        "/ __|",
        "\\__ \\",
        "|___/",
        "     ",
        "     ",
    },
    // t
    {
        " _   ",
        "| |  ",
        "| |_ ",
        "| __|",
        "| |_ ",
        " \\__|",
        "     ",
        "     ",
    },
    // u
    {
        "       ",
        "       ",
        " _   _ ",
        "| | | |",
        "| |_| |",
        " \\__,_|",
        "       ",
        "       ",
    },
    // v
    {
        "       ",
        "       ",
        "__   __",
        "\\ \\ / /",
        " \\ V / ",
        "  \\_/  ",
        "       ",
        "       ",
    },
    // w
    {
        "          ",
        "          ",
        "__      __",
        "\\ \\ /\\ / /",
        " \\ V  V / ",
        "  \\_/\\_/  ",
        "          ",
        "          ",
    },
    // x
    {
        "      ",
        "__  __",
        "\\ \\/ /",
        " >  < ",
        "/_/\\_\\",
        "      ",
        "      ",
        "      ",
    },
    // y
    {
        "       ",
        "       ",
        " _   _ ",
        "| | | |",
        "| |_| |",
        " \\__, |",
        "  __/ |",
        " |___/ ",
    },
    // z
    {
        "     ",
        "     ",
        " ____",
        "|_  /",
        " / / ",
        "/___|",
        "     ",
        "     ",
    },
};

const tuil_font_t tuil_font_doom = {
    "doom",
    8,
    {
        ['A'] = (const char**)char_ptrs_upper_doom[0],
        ['a'] = (const char**)char_ptrs_lower_doom[0],
        ['B'] = (const char**)char_ptrs_upper_doom[1],
        ['b'] = (const char**)char_ptrs_lower_doom[1],
        ['C'] = (const char**)char_ptrs_upper_doom[2],
        ['c'] = (const char**)char_ptrs_lower_doom[2],
        ['D'] = (const char**)char_ptrs_upper_doom[3],
        ['d'] = (const char**)char_ptrs_lower_doom[3],
        ['E'] = (const char**)char_ptrs_upper_doom[4],
        ['e'] = (const char**)char_ptrs_lower_doom[4],
        ['F'] = (const char**)char_ptrs_upper_doom[5],
        ['f'] = (const char**)char_ptrs_lower_doom[5],
        ['G'] = (const char**)char_ptrs_upper_doom[6],
        ['g'] = (const char**)char_ptrs_lower_doom[6],
        ['H'] = (const char**)char_ptrs_upper_doom[7],
        ['h'] = (const char**)char_ptrs_lower_doom[7],
        ['I'] = (const char**)char_ptrs_upper_doom[8],
        ['i'] = (const char**)char_ptrs_lower_doom[8],
        ['J'] = (const char**)char_ptrs_upper_doom[9],
        ['j'] = (const char**)char_ptrs_lower_doom[9],
        ['K'] = (const char**)char_ptrs_upper_doom[10],
        ['k'] = (const char**)char_ptrs_lower_doom[10],
        ['L'] = (const char**)char_ptrs_upper_doom[11],
        ['l'] = (const char**)char_ptrs_lower_doom[11],
        ['M'] = (const char**)char_ptrs_upper_doom[12],
        ['m'] = (const char**)char_ptrs_lower_doom[12],
        ['N'] = (const char**)char_ptrs_upper_doom[13],
        ['n'] = (const char**)char_ptrs_lower_doom[13],
        ['O'] = (const char**)char_ptrs_upper_doom[14],
        ['o'] = (const char**)char_ptrs_lower_doom[14],
        ['P'] = (const char**)char_ptrs_upper_doom[15],
        ['p'] = (const char**)char_ptrs_lower_doom[15],
        ['Q'] = (const char**)char_ptrs_upper_doom[16],
        ['q'] = (const char**)char_ptrs_lower_doom[16],
        ['R'] = (const char**)char_ptrs_upper_doom[17],
        ['r'] = (const char**)char_ptrs_lower_doom[17],
        ['S'] = (const char**)char_ptrs_upper_doom[18],
        ['s'] = (const char**)char_ptrs_lower_doom[18],
        ['T'] = (const char**)char_ptrs_upper_doom[19],
        ['t'] = (const char**)char_ptrs_lower_doom[19],
        ['U'] = (const char**)char_ptrs_upper_doom[20],
        ['u'] = (const char**)char_ptrs_lower_doom[20],
        ['V'] = (const char**)char_ptrs_upper_doom[21],
        ['v'] = (const char**)char_ptrs_lower_doom[21],
        ['W'] = (const char**)char_ptrs_upper_doom[22],
        ['w'] = (const char**)char_ptrs_lower_doom[22],
        ['X'] = (const char**)char_ptrs_upper_doom[23],
        ['x'] = (const char**)char_ptrs_lower_doom[23],
        ['Y'] = (const char**)char_ptrs_upper_doom[24],
        ['y'] = (const char**)char_ptrs_lower_doom[24],
        ['Z'] = (const char**)char_ptrs_upper_doom[25],
        ['z'] = (const char**)char_ptrs_lower_doom[25],
    }
};
